# Generated by Django 5.0.1 on 2024-02-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_artisan_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
