# Generated by Django 5.0.1 on 2024-03-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_artisan_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artisan',
            options={'permissions': (('can_add_items', 'Can add items'),)},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('can_add_items', 'Can add items'),)},
        ),
        migrations.AlterModelManagers(
            name='artisan',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='user_permissions',
        ),
    ]
