# Generated by Django 5.0.1 on 2024-03-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_customer_managers_remove_customer_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artisan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
